---
name: Sync with upstream

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 1 * * *"  # UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    # Cannot use default GITHUB_TOKEN, as PRs created by this token will not trigger a new workflow run.
    # Use a Fine-grained Personal Access Token (PAT) with scopes:
    # - contents: Read and Write
    # - pull-requests: Read and Write
    # https://docs.github.com/en/actions/how-tos/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#triggering-a-workflow-from-a-workflow
    # permissions:
    #   actions: write
    #   contents: write
    #   # Also Settings > Actions > General
    #   # [x] Allow GitHub Actions to create and approve pull requests
    #   pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Setup just
        uses: extractions/setup-just@v3

      - name: Update adlist
        run: just adlist

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          token: ${{ secrets.HOSTS_PR_TOKEN }}
          title: 'Update Adlist'
          commit-message: 'Update Adlist'
          body: |
            Update Adlist
          branch: update-adlist
